.\" Copyright (C) 2014 Red Hat, Inc. All Rights Reserved.
.\" Written by Jan Chaloupka <jchaloup@redhat.com>

.TH VISUALIZE  1 2014-07-04 "Linux" "Code Assistant Manual"
.SH NAME
visualize \- visualize source code
.SH DESCRIPTION

Describe all files for each source code page (keyworddb, keyword, vis page keyworddb, ...)

.SH OPTIONS
Never do --dest=~/Documents/..., i.e. no ~ symbol (I should fix this)



.SH FILES
.LP
.PD .1v
.TP 20
.B /etc/cgrules.d
.RS 4
default libcgroup configuration files directory
.RE
.B /etc/cgconfig.conf
RS 4
default libcgroup configuration file
.RE
.PD .


.SH SEE ALSO
cgconfig.conf (5), cgrulesengd (8)
